### ISSUE TITLE
Is the entropy bottleneck layer the network of side information?

### ISSUE THREAD

**Issue by yangjy0826** [tensorflow/compression#10]
Hi,

I found that in your example bls2017.py, a function `tfc.EntropyBottleneck` is called. Does this function work for the side information network (mentioned in the paper 'Variational Image Compression With a Scale Hyperprior')?

Thank you so much!

**Comment by jonycgn** [comment]
Hi, `tfc.EntropyBottleneck` is a layer that's instantiated. It implementes a fully factorized, unconditional entropy model, so it can be used to model the side information itself (z in that paper), but not for conditional models (y).

Hope that this answers your question. I'm closing this issue. Please ask any follow-up questions in the [Google group](https://groups.google.com/forum/#!forum/tensorflow-compression). Thanks!
