### ISSUE TITLE
Checkerboard artifacts in reconstructed image

### ISSUE THREAD

**Issue by parthnatekar** [tensorflow/compression#110]
### Discussed in https://github.com/tensorflow/compression/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **parthnatekar** November  5, 2021</sup>
Hi, I'm training an mselpips model on a custom dataset.

I'm getting checkerboard artifacts in my reconstructed image, shown below. This is a part of the background and should hence be completely zero
![Screenshot from 2021-11-05 17-11-55](https://user-images.githubusercontent.com/33252453/140591014-722ae69c-27ac-4a96-9816-5ca66f888f5a.png)

Why does this happen? Do I need to change my hyperparameters?

Thanks
</div>

**Comment by jonycgn** [comment]
Hi, it doesn't seem like this is a problem in the library. Closing since there is already a discussion topic.
