### ISSUE TITLE
pack() missing 1 required positional argument: 'arrays'

### ISSUE THREAD

**Issue by prmudgal** [tensorflow/compression#126]
**Describe the bug**
I clone Hific repo from [here ](https://github.com/tensorflow/compression/tree/e4263cd9fb676d0b40d14bc596e86be9e0b1b984/models/hific).
While compressing the image produces below error-
 pack() missing 1 required positional argument: 'arrays'.
The same code ran fine until few weeks back. Did anything change in the trained models

**To Reproduce**
git clone https://github.com/tensorflow/compression
cd compression/models
conda create --name hific python=3.7 cudatoolkit=10.0 cudnn
conda activate hific
pip install -r hific/requirements.txt
python tfci.py compress <model> <PNG file>

Error:

  File "tfci.py", line 326, in main
    args.target_bpp, args.bpp_strict)
  File "tfci.py", line 120, in compress
    bitstring = compress_image(model, input_image)
  File "tfci.py", line 105, in compress_image
    packed.pack(tensors)
TypeError: pack() missing 1 required positional argument: 'arrays'

**Expected behavior**
Image should be compressed producing *.tfci

**System (please complete the following information):**
 - OS
 - Python version 3.7
 - TensorFlow version 1.15
 - tensorflow-compression 1.3

**Comment by jonycgn** [comment]
Hi – nothing changed in the trained models.

Note that the requirements for `tfci.py` and running the HiFiC training code are different:

For using `tfci.py`, just install the latest version of TFC (`pip install tensorflow-compression`). This will allow you to run all the pre-trained models, including HiFiC.

For using the HiFiC code in `models/hific`, install the packages in `hific/requirements.txt`, but don't run `tfci.py`. (In principle, you can run `tfci.py` with TFC 1.3 as well, but you will need to check out an older version. The one at head is designed to run with the latest version of TFC.)

**Comment by prmudgal** [comment]
It worked after upgrading TFC to latest version. 
Thank you.
