### ISSUE TITLE
metagraphs link is outdated

### ISSUE THREAD

**Issue by Aly-hosny** [tensorflow/compression#130]
when I try to use a target_bpp in hific, the code tries to downlaod and cache the metagraphs for the specified model and it the link to download is outdated or the files has been deleted.
is it possible to reupload them or just share the files with me
"https://storage.googleapis.com/tensorflow_compression/metagraphs/hific-mi.models"

**Comment by jonycgn** [comment]
Hi Aly, thanks for letting us know. It should be fixed now. You can use `--target_bpp` with the model identifier `hific`. Note that the target bpp might not be matched very accurately for HiFiC, since there's only three options (trained RD points) to choose from per image.

**Comment by hyunW3** [comment]
I cannot access these links..  Is there any plan to update these three links?
- "[storage.googleapis.com/tensorflow_compression/metagraphs/hific-mi.models](https://storage.googleapis.com/tensorflow_compression/metagraphs/hific-lo.models)"
- "[storage.googleapis.com/tensorflow_compression/metagraphs/hific-mi.models](https://storage.googleapis.com/tensorflow_compression/metagraphs/hific-mi.models)"
- "[storage.googleapis.com/tensorflow_compression/metagraphs/hific-mi.models](https://storage.googleapis.com/tensorflow_compression/metagraphs/hific-hi.models)"
