### ISSUE TITLE
Is it possible to get the encoded sub-patches from a encoded image directly?

### ISSUE THREAD

**Issue by smujiang** [tensorflow/compression#15]
Hi folks,
I'm wondering if it is possible to get the encoded sub-patches from a encoded image directly, rather than decoding the encoded image and extract the sub-patches then encode the sub-patch again.

Any one with clues will  be appreciated.

**Comment by jonycgn** [comment]
Hi smujiang, I'm not sure I understand the question. Please give a bit more context on what you are trying to do.

Also, unless this is a concrete feature request, please direct questions to our [Google group](https://groups.google.com/forum/#!forum/tensorflow-compression). We're trying to keep Github "issues" to bug reports or feature requests which require future changes to the library code.

I'm closing this issue. I'll be awaiting your elaborated question in the Google group!
