### ISSUE TITLE
Running all tests fail in Colab Pro+, Premium, High-Ram environment (A100-SXM4-40GB)

### ISSUE THREAD

**Issue by Nikolai10** [tensorflow/compression#155]
**Running all tests fail in Colab Pro+, Premium, High-Ram environment (A100-SXM4-40GB)**

**To Reproduce**
Working example (default Colab with Tesla T4 GPU):
https://colab.research.google.com/drive/1RP4etsIfIrLcXufhIJUqVa-YbNnBIovn?usp=sharing

Exact same example (Colab Pro+, Premium, High-Ram environment (A100-SXM4-40GB):
https://colab.research.google.com/drive/1-LtV3iVeQ7kpym0q1QY7_yveOMsVDTv9?usp=sharing

-> tests fail.

**Expected behavior**
expected output similar to the working example.

**System (please complete the following information):**
everything contained within Notebooks.

**Additional context**
The same pattern is present within TFC 2.8.X (seems to be specifically related to the A100 environment)

Any ideas? Happy to run some experiments if you provide me with some guidance. 
Thanks!

**Comment by jonycgn** [comment]
Hi, it looks like the first problem is simply a double escaping issue (it should be `\`s instead of `\\`s). A fix is underway.

For the second, this is quite curious. Most of the tests seem to fail because of numerical imprecision. Does the A100 platform use a different floating point format?

**Comment by Nikolai10** [comment]
Thanks for your feedback!

It seems like starting with the Ampere-GPUs, Nvidia has introduced a new format "TensorFloat-32", see https://blogs.nvidia.com/blog/2020/05/14/tensorfloat-32-precision-format/.

By adding the following lines to all_tests.py
```
import tensorflow as tf
tf.config.experimental.enable_tensor_float_32_execution(False)
```
the [traditional float32 precision](https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_tensor_float_32_execution) is used which indeed resolves the issue.

I have also noticed that similar observations have been made on other projects, see for example https://dev-discuss.pytorch.org/t/pytorch-and-tensorfloat32/504.

What do you think? Do you have any recommendations for TF32/ TFC?

**Comment by jonycgn** [comment]
Hi, this would explain it. Thanks for researching this! I think for the purposes of the unit tests, we'll disable the TensorFloat32 format using the command you mentioned. The fact that these fail with that format doesn't necessarily imply that training or inference doesn't work (I wouldn't expect major problems).

**Comment by Nikolai10** [comment]
Thanks for your help!

I have already tried it out: https://github.com/Nikolai10/SwinT-ChARM - I was just a little confused at the beginning of my experiments and wanted to be sure that everything works as expected.
