### ISSUE TITLE
the problem of print

### ISSUE THREAD

**Issue by shellhuang1227** [tensorflow/compression#25]
hello,

I ran the  example bls2017 to compress images. The file "compressed.bin" could be generated, but there was nothing to print (MSE, PSNR etc.). Could you help me solve this problem?

Thank you very much!

**Comment by jonycgn** [comment]
Hi,

please try using --verbose.

Best,
Johannes

**Comment by shellhuang1227** [comment]
Thank you very much.  The information has been printed in this way.
