### ISSUE TITLE
The problem about quantization

### ISSUE THREAD

**Issue by shellhuang1227** [tensorflow/compression#26]
Hello,

I want to achieve the quantization value of the image and map the quantization value to other sequence in my research. But I did not understand EntropyBottleneck at all, so I am confused with the following code and can not find the quantization value. Can you help me to get the quantization value?
  y = analysis_transform(x, args.num_filters)
  entropy_bottleneck = tfc.EntropyBottleneck()
  string = entropy_bottleneck.compress(y)
  string = tf.squeeze(string, axis=0)
 
 # Transform the quantized image back (if requested).
  y_hat, likelihoods = entropy_bottleneck(y, training=False)
  x_hat = synthesis_transform(y_hat, args.num_filters)

Thank you very much.

**Comment by jonycgn** [comment]
Hi,

y_hat corresponds to the quantized latent representation of the image. It only contains integer values.

Best,
Johannes

**Comment by shellhuang1227** [comment]
Hello,

Thanks for your reply. 
The q in your paper do not appear in your code, so the quantization value is just y_hat and do not consider q in code?
By the way, how can I get the level of the y_hat (i.e. the quantitative level)?

Thank you very much.
