### ISSUE TITLE
The question about quantization

### ISSUE THREAD

**Issue by shellhuang1227** [tensorflow/compression#27]
Hello,

Thanks for your reply to my previous question. I have some new questions to consult you.

1. The q in your paper do not appear in your code, so the quantization representation is just y_hat and do not consider q in code? I ran the code and the value of y_hat is not an integer, just as followings:
[[[[ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  1.0139648   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   ...
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  2.0139647   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]]

  [[ 0.59345233  1.0139648   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233 -0.9860352   0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  1.0139648   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   ...
   [ 0.59345233 -1.9860352   0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  1.0139648   0.13712975 ...  0.1063276  -0.2717389  -0.42567667]]

  [[ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233 -1.9860352   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   ...
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]]

  ...

  [[ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   ...
   [ 0.59345233 -0.9860352   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  1.0139648   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  1.0139648   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]]

  [[ 0.59345233 -0.9860352   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233 -0.9860352   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   ...
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233 -0.9860352   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]]

  [[ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   ...
   [ 0.59345233 -0.9860352   0.13712975 ...  0.1063276  -0.2717389   -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]
   [ 0.59345233  0.01396477  0.13712975 ...  0.1063276  -0.2717389  -0.42567667]]]]
By the way, how can I get the level of the y_hat (i.e. the quantitative level), as you can see there are many ellipses in the above value?

2. Is the compressed string made up of binary streams? How can I open the file of compressed.bin as I want to use the content of the compressed string if it is a binary stream.

Thank you very much.

**Comment by jonycgn** [comment]
Hello,

you're right, I was not very precise. y_hat doesn't strictly contain integer values. It's integer values with a channel-specific float offset (the offset is the same for all values in a given channel).

I don't know what you mean by quantitative level. The ellipses are there because you're printing a large array as text, and numpy won't print the entire array in this case. It's a display issue.

Regarding your second question, I don't know what you mean. The compressed string is binary, yes.

I'm closing this, because this is for discussing bugs in our code. If you have questions how to use the library, please ask them in the mailing list. There are more people there to help. https://groups.google.com/forum/#!forum/tensorflow-compression
