### ISSUE TITLE
Problems about images used to train

### ISSUE THREAD

**Issue by WXIAO-TJ** [tensorflow/compression#29]
Hello,
        In your paper"END-TO-END OPTIMIZED IMAGE COMPRESSION" , i find that you used  6507 ImageNet images as training set .But i didn't find them. Could you tell me how to download them?

Thank you very much.

**Comment by jonycgn** [comment]
This is not a bug. Please ask questions on the mailing list.

The ImageNet examples are not available publicly. The appendix in the paper describes the preprocessing we applied.
