### ISSUE TITLE
Cudnn version

### ISSUE THREAD

**Issue by xinziXu** [tensorflow/compression#33]
Hi, I used commad lines to config the environment:
```
conda create --name ENV_NAME python=3.6 cudatoolkit=10.0 cudnn
conda activate ENV_NAME
pip install tensorflow-gpu tensorflow-compression
```
My conda list is:

> _libgcc_mutex             0.1                        main
> absl-py                   0.7.1                     <pip>
> astor                     0.8.0                     <pip>
> ca-certificates           2019.5.15                     1
> certifi                   2019.6.16                py36_1
> cudatoolkit               10.0.130                      0
> cudnn                     7.6.0                cuda10.0_0
> gast                      0.2.2                     <pip>
> google-pasta              0.1.7                     <pip>
> grpcio                    1.23.0                    <pip>
> h5py                      2.9.0                     <pip>
> Keras-Applications        1.0.8                     <pip>
> Keras-Preprocessing       1.1.0                     <pip>
> libedit                   3.1.20181209         hc058e9b_0
> libffi                    3.2.1                hd88cf55_4
> libgcc-ng                 9.1.0                hdf63c60_0
> libstdcxx-ng              9.1.0                hdf63c60_0
> Markdown                  3.1.1                     <pip>
> ncurses                   6.1                  he6710b0_1
> numpy                     1.17.0                    <pip>
> openssl                   1.1.1c               h7b6447c_1
> pip                       19.2.2                   py36_0
> protobuf                  3.9.1                     <pip>
> python                    3.6.9                h265db76_0
> readline                  7.0                  h7b6447c_5
> scipy                     1.3.1                     <pip>
> setuptools                41.0.1                   py36_0
> six                       1.12.0                    <pip>
> sqlite                    3.29.0               h7b6447c_0
> tensorboard               1.14.0                    <pip>
> tensorflow-compression    1.2                       <pip>
> tensorflow-estimator      1.14.0                    <pip>
> tensorflow-gpu            1.14.0                    <pip>
> termcolor                 1.1.0                     <pip>
> tk                        8.6.8                hbc83047_0
> Werkzeug                  0.15.5                    <pip>
> wheel                     0.33.4                   py36_0
> wrapt                     1.11.2                    <pip>
> xz                        5.2.4                h14c3975_4
> zlib                      1.2.11               h7b6447c_3
> 

And I ran test code successfully. However, I met an error when running tfci.py. The error says

> Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

I searched on the Internet and it says that the tensorflow-gpu version doesn't match with cudnn+cuda version.  I use tensorflow-gpu1.14.0. What's your cudnn version?

**Comment by jonycgn** [comment]
Refer to https://www.tensorflow.org/install/gpu for the TensorFlow GPU requirements.

Have you installed NVIDIA drivers 410.x or higher?

**Comment by xinziXu** [comment]
Yes, I tried to use python3.6 instead of anaconda. It runs OK. Thank you.
