### ISSUE TITLE
How to pick the 6507 images as training set

### ISSUE THREAD

**Issue by Mistariano** [tensorflow/compression#34]
Hi,

Thanks a lot for your brilliant work. :)
I just wonder how you extract the 6507-image training dataset from imagenet as you mentioned in the paper _End To End Optimized Image Compression_. Did you pick the images just randomly or by following any rules?

BTW I read the earlier issue #29 and found that I should send a email to ask the question, but I have no idea how to send an email to a github repository's mailing list...

Would you please help me? Thanks so much

**Comment by jonycgn** [comment]
Hi,

there was some preprocessing involved, such as downsampling, to reduce artifacts from JPEG compression. The images were chosen randomly, and images that were too small to allow at least some downsampling were ignored. The details to that are in the appendix of the paper.

The mailing list is [here](https://groups.google.com/forum/#!forum/tensorflow-compression).

Best,
Johannes
