### ISSUE TITLE
Decode some incorrect pictures

### ISSUE THREAD

**Issue by xylLike** [tensorflow/compression#37]
Hello, when I was trying this code，In the same intermediate file, sometimes it is normal to decode the picture, sometimes it is abnormal to decode the picture

**Comment by xylLike** [comment]
![0NP4LDAA5J$R1E%(6JHH4KU](https://user-images.githubusercontent.com/32838725/71791963-e33bb480-3071-11ea-8200-417cd7500ce5.jpg)

**Comment by jonycgn** [comment]
Hi,

this seems to be a regression, maybe caused by a change in TensorFlow. Which model is this? Can you try to run the decoder without GPU support, and see if the problem is still there?

Thanks!

**Comment by xylLike** [comment]
> Hi,
> 
> this seems to be a regression, maybe caused by a change in TensorFlow. Which model is this? Can you try to run the decoder without GPU support, and see if the problem is still there?
> 
> Thanks!

>When I try to run the decoder without GPU support，The problem has been solved。
>Thank you very much！

**Comment by jonycgn** [comment]
It should work on GPU as well. Reopening so we can look into the problem.

**Comment by xylLike** [comment]
On the basis of bmshj2018.py code, I changed some network structures, except entropy coding。when I try to run the encoder and decoder without GPU support, this problem will be solved

**Comment by jonycgn** [comment]
I see, so this is your own model, not one of our pre-trained ones. In that case, we can close it. Thanks!
