### ISSUE TITLE
Tfci.py looking for CUDA libs even if tensorflow-gpu is not installed

### ISSUE THREAD

**Issue by medgives** [tensorflow/compression#38]
I'm trying to encode few images with the pretrained models. 
The system is a VM running on a cluster, OS is Ubuntu 18.04. Python is 3.6.9, tensorflow is 1.15 and tensorflow-compression is 1.3. The system has no GPU, so I can't use tensorflow-gpu.
Following the readme file instructions, I run:
`python3 tfci.py compress bmshj2018-factorized-mse-3 test_img_001.png`

then I get the following output:
`2020-02-22 22:41:08.854368: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/user/research/codecs/kakadu:/home/user/research/codecs/kakadu
2020-02-22 22:41:08.854410: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-02-22 22:41:08.854451: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (matlabWS): /proc/driver/nvidia/version does not exist
2020-02-22 22:41:08.854810: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
2020-02-22 22:41:08.889214: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3491910000 Hz
2020-02-22 22:41:08.892134: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4c44dc0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-22 22:41:08.892369: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
I0222 22:41:09.164153 140027371087680 saver.py:1503] Saver not created because there are no variables in the graph to restore`

It's looking for CUDA libs, even if there's no GPU. It's like if it's stuck with using tensorflow-gpu.
I run the previous version of tensorflow-compression in the past on the exact same system without any problems, so I think it's a bug with the 1.3.

Thanks for the help.

**Comment by jonycgn** [comment]
Hi,

I actually suspect some problem in TF 1.15, since this project doesn't actually have any GPU-specific code. Have you tried running any other TensorFlow code? Like simply `python3 -c "import tensorflow"`?

Please also post a stack trace, I'd like to know in which line of tfci.py the code fails.

Thanks!

**Comment by medgives** [comment]
HI,
`python3 -c "import tensorflow"` works without any problems. The `python -m tensorflow_compression.python.all_test` command suggested in the readme also returns no errors.

There's no stack trace related to tfci.py, which in facts makes me think too it's some kind of problem with TF.

I think it's also worth mentioning I get the exact same problem on my laptop (also running Ubuntu 18.04, TF 1.15, Python 3.6 and tf-compression 1.3).

Thanks for the help

**Comment by jonycgn** [comment]
I can't reproduce this on my Mac (running Python 3.7, otherwise same versions). Just compressed and decompressed an image with the model you mentioned successfully.

I will need more time to look into this on Linux. In the mean time, if you have any updates, please post them here.

**Comment by medgives** [comment]
Ok, I think I discovered what's the problem: it's just a console output problem. The .tfci file is correctly created and it appears to be fine (I was able to decompress it also). My fault, I should have checked before opening the issue.

**Comment by vedantshandilya** [comment]
I'm not able to install ttensorflow-compression
