### ISSUE TITLE
The detailed settings for the results optimized for MS-SSIM

### ISSUE THREAD

**Issue by zzs1994** [tensorflow/compression#39]
Hi, thanks for your excellent work and for sharing the code!

I could not find the detailed settings for the results optimized for MS-SSIM here.

Since the magnitude of the MSE-based distortion loss is quite different from the MS-SSIM-based distortion loss, I wonder what setting of lambda (the trade-off parameter) is used in the experiment measured by MS-SSIM. Hope to hear your response, thanks!

**Comment by jonycgn** [comment]
Hi, the value of lambda for MS-SSIM is typically in the range 1e0 to 1e2.
