### ISSUE TITLE
Issue while training with Resource Exchaust Error. I have configuration as per attached image and gpu usage while training on png dataset. 

### ISSUE THREAD

**Issue by MandeepSinghthakur** [tensorflow/compression#4]
![capture](https://user-images.githubusercontent.com/11257482/43467904-9f467e76-9497-11e8-8fc0-deda28e8de53.PNG)
![configration](https://user-images.githubusercontent.com/11257482/43467919-a4fb2a92-9497-11e8-89cf-79db3f2d6760.PNG)

**Comment by MandeepSinghthakur** [comment]
googled it and seems like 'm running out of GPU memory(dumb clearly shown by gpu usage). It means i need to train it on multiple gpu's  or cloud ?

**Comment by jonycgn** [comment]
How many training images are you using, and what is their pixel size?

**Comment by MandeepSinghthakur** [comment]
around 11000 images and they were  huge files. going to try resize them and try.

**Comment by jonycgn** [comment]
The training implementation in bls2017.py just loads all the training images into memory upfront, so they need to all fit into your GPU memory. Just use fewer/smaller training images. This kind of model doesn't really need a huge amount of training data.

Closing this now. In the future, please use the Google group for things like this ("issues" are more for bugs in our code). Thanks!
