### ISSUE TITLE
undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv on Linux

### ISSUE THREAD

**Issue by trougnouf** [tensorflow/compression#40]
Using Arch Linux and gcc 9.3.0, python 3.8, and tensorflow 2.1, I get the following error:
```
>>> import tensorflow_compression
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trougnouf/.local/lib/python3.8/site-packages/tensorflow_compression/__init__.py", line 30, in <module>
    from tensorflow_compression.python.entropy_models.continuous_batched import *
  File "/home/trougnouf/.local/lib/python3.8/site-packages/tensorflow_compression/python/entropy_models/continuous_batched.py", line 20, in <module>
    from tensorflow_compression.python.entropy_models import continuous_base
  File "/home/trougnouf/.local/lib/python3.8/site-packages/tensorflow_compression/python/entropy_models/continuous_base.py", line 24, in <module>
    from tensorflow_compression.python.ops import range_coding_ops
  File "/home/trougnouf/.local/lib/python3.8/site-packages/tensorflow_compression/python/ops/range_coding_ops.py", line 26, in <module>
    ops = namespace_helper.get_ops(load_library.load_op_library(
  File "/usr/lib/python3.8/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/trougnouf/.local/lib/python3.8/site-packages/tensorflow_compression/python/ops/../../cc/libtensorflow_compression.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```
Note that I had to add `'Programming Language :: Python :: 3.8'` in build_pip_pkg.py and make a change (`  if "linux" in ctx.os.name:    library_filename = "libtensorflow_framework.so.2"`) in workspace.bzl to compile in the first place.

I tried compiling with `bazel run -c opt --copt "-D_GLIBCXX_USE_CXX11_ABI=1" :build_pip_pkg` as that solution came up a few times, but that didn't get rid of the error.

I know that newer versions of Linux / libs are not officially supported but I would rather not learn TensorFlow 1 now if I can help it, so I'm posting this as a placeholder.

**Comment by trougnouf** [comment]
Fixed. I just had to remove 
```
        "-std=c++11",
        "-D_GLIBCXX_USE_CXX11_ABI=1",
```
from tensorflow_compression/cc/BUILD, then compile with `bazel run -c opt :build_pip_pkg`

**Comment by trougnouf** [comment]
I made an AUR/Arch package https://aur.archlinux.org/packages/python-tensorflow-compression-git/ with the patch on https://aur.archlinux.org/cgit/aur.git/tree/arch_compression.patch?h=python-tensorflow-compression-git

**Comment by jonycgn** [comment]
Hi, thanks for this.

If by "learning TF 1" you mean learning to write your model in graph mode, this will still be necessary unless you use the new entropy model implementations (under tensorflow_compression/python/entropy_models).

The EntropyBottleneck and GaussianConditional classes etc., which our examples and the documentation are based on, aren't compatible with eager mode (neither in TF1 nor in TF2, where eager mode is the default).
