### ISSUE TITLE
When the model running in aGPU，we will get different result each time

### ISSUE THREAD

**Issue by rongpan123** [tensorflow/compression#41]
When the trained model compress or decompress a image in a GPU, we got different result each time. But when compress or decompress image in cpu, we will get correct result (only one)each time

**Comment by jonycgn** [comment]
Hi,

can you please be more specific:

Which model are you running?
Have you made any modifications to the code?
How big are the differences you are seeing?

Thanks.

**Comment by rongpan123** [comment]
I've found the reason. This is mainly due to cuda version conflicts. But I have another doubt, when the size of image is odd number, the output size of the feature-map in the last layer of SynthesisTransform network is not an integer multiple of stride_up in the last layer(input: (1,1024,74,192),output_shape:(1,2048,1401,3),stride_up:2)

**Comment by rongpan123** [comment]
I've found the reason. This is mainly due to cuda version conflicts. Thank you.
