### ISSUE TITLE
Problem when training bls2017.py

### ISSUE THREAD

**Issue by MahdyZ** [tensorflow/compression#42]
**Describe the bug**
When I execute this command  **python3 bls2017.py --verbose train --train_glob="images/*.png"**, the training is first appears to work well but after that, this error occures:
![image](https://user-images.githubusercontent.com/47226413/80394682-1668b480-88aa-11ea-9e28-c5d2df6c812a.png)
After that, the file "train" appears but when decompressing compressed images with bls2017.py, the result image is all black.

**Expected behavior**
I think the reconstruction problem is the result of the training error so i expect to have a solution for the training problem.

**System please complete the following information):**
 - ubuntu 18.04
 - python 3.6.9
 - TensorFlow 1.15.0
 - tensorflow-compression 1.3

**Comment by jonycgn** [comment]
It looks like somewhere in your training set, there is an image that is smaller than your patch size (256x256 pixels).

I'm closing this bug. Please reopen if removing that image doesn't solve your problem.
