### ISSUE TITLE
wrong reconstructed image test on gpu

### ISSUE THREAD

**Issue by qianqiusuili** [tensorflow/compression#44]
**Describe the bug**
Based on  'bmshj2018.py', don't change anything, I just trained a new model with 30000 steps, compressed and decompressed my test imgae (a 'png' type image with size '2560x3840') on Gpu, the recon image is wrong. There is no problem tested on cpu. The same step ckpt encode and decode 'kodim01.png' whcih size is '512x768'  on gpu, the recon image is right, even endode on gpu and decode on cpu

**Wrong decompressed img**
![rain1 png tfci](https://user-images.githubusercontent.com/28892519/81169019-ae614f00-8fca-11ea-8e48-f0b1a67a0ee9.png)

**System**
 - ubuntu 16.04
 - Python 3.6.7
 - conda install tensorFlow-gpu== 1.15.0
 - tensorflow-compression==1.3
 - gpu version [GeForce GTX 1080 Ti]

**Additional context**
Actually, my test image test on your releaze mode named 'mbt2018-mean-mse-1' are always correct no matter gpu or cpu  been used when coding or decoding. It means GPU and CPU can be mixed used when coding and decoding eventhough recon sigma haved tiny difference.

**Comment by qianqiusuili** [comment]
After train more step, about 120000，I compress and decompress the same picture again,  reconstruced image is right no matter use gpu or cpu.

**Comment by jonycgn** [comment]
I think you may be running into a problem that we described in [this paper](https://openreview.net/forum?id=S1zz2i0cY7). Please take a look.

One solution is to use integer networks for the conditional entropy model, as described in the paper, which eliminates the stability problem across multiple hardware platforms. The other solution is to make sure that the encoder and the decoder run on identical hardware, and that the hardware computes convolutions in a deterministic way.

I'm closing this bug for now, assuming that this is the problem you are seeing. If not, please reopen.
