### ISSUE TITLE
Reimplementation on learned image compression with Pytorch toolbox

### ISSUE THREAD

**Issue by liujiaheng** [tensorflow/compression#45]
Thanks for your wonderful works on learned image compression.
Our team has reimplemented the ' End-to-end Optimized Image Compression(ICLR17)' and 'Variational image compression with a scale hyperprior(ICLR18)' with Pytorch toolbox.
Besides, our team has released our code on Github.
ICLR17 link: https://github.com/liujiaheng/iclr_17_compression
ICLR18 link: https://github.com/liujiaheng/compression

Thanks.

**Comment by jonycgn** [comment]
Thanks for the note!
