### ISSUE TITLE
undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by YujunHuang063** [tensorflow/compression#46]
when I run:
`import tensorflow_compression`
that's an error:
`tensorflow.python.framework.errors_impl.NotFoundError: /data/huangyujun/anaconda2/envs/tensorflow1/lib/python3.6/site-packages/tensorflow_compression/python/ops/../../cc/libtemsorflow_compression.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`

I have tried version 1.3, 1.2, 1.2b2, the same error raised. 

Thanks for the help!

**Comment by YujunHuang063** [comment]
![1591105083(1)](https://user-images.githubusercontent.com/37411279/83526683-6118c480-a519-11ea-8060-bf60dc367819.jpg)

**Comment by YujunHuang063** [comment]
This problem has been solved. I run
`pip install tensorflow-gpu=1.15`
to install tensorflow instead of:
`conda install tensorflow-gpu=1.15`

**Comment by jonycgn** [comment]
Hi Yujun,

yes, this problem is described [here](https://github.com/tensorflow/compression#anaconda).

Closing this issue now.
