### ISSUE TITLE
Could you upload the trained model

### ISSUE THREAD

**Issue by chouqin3** [tensorflow/compression#5]
The project works, but lack of the model, could you upload?

**Comment by jonycgn** [comment]
Hi. We are planning some updates in the future, potentially providing a fully trained model that you can just run. At the moment, this is a bit tricky.

In the mean time, there's a Matlab implementation with parameters [here](http://www.cns.nyu.edu/~lcv/iclr2017/) (although the boundary handling in that model is different). Hope this helps!

Keeping this issue open, so we can get back to it eventually.

**Comment by jonycgn** [comment]
Fixed with commit 540110aa2b4574cba663b11dd49660acffdd6baf. This allows loading and using pre-trained model graphs to compress and decompress images.
