### ISSUE TITLE
Unable to retain the original resolution on reconstruction.

### ISSUE THREAD

**Issue by PrasangaDhungel** [tensorflow/compression#54]
Hello,

I am compressing an image of resolution 426 x 240. 

The architecture for analysis transformation is:

```
self._layers = [
            tfc.SignalConv2D(
                self.num_filters, (3, 3), name="layer_0", corr=True, strides_down=2,
                padding="same_zeros", use_bias=True,
                activation=tfc.GDN(name="gdn_0")),

            tfc.SignalConv2D(
                self.num_filters, (3, 3), name="layer_1", corr=True, strides_down=2,
                padding="same_zeros", use_bias=True,
                activation=tfc.GDN(name="gdn_1")),

            tfc.SignalConv2D(
                self.num_filters, (3, 3), name="layer_2", corr=True, strides_down=2,
                padding="same_zeros", use_bias=True,
                activation=tfc.GDN(name="gdn_2")),

            tfc.SignalConv2D(
                self.num_filters, (3, 3), name="layer_3", corr=True, strides_down=2,
                padding="same_zeros", use_bias=True,
                activation=None),
        ]

```
So the shape of latent representation(excluding batch and channel) is 27 x 15.

The architecture of synthesis transform is exactly inverse of the analysis transform. But the shape of the reconstructed image is 432 x 240. I tried different padding options, but I couldn’t figure out what combination would get me the original shape. Some combinations would reconstruct the output of the same height but different width, and some would reconstruct the output of the same width but different height. This problem seems not only for this specific resolution but also for other resolutions as well (when the height and width aren’t the multiple of 16).

Here is a complete network architecture, https://github.com/tukilabs/Video-Compression-Net/blob/master/utils/network.py
(class AnalysisTransform and class SynthesisTransform)

PS, I’m using this wonderful work for video compression.

**Comment by jonycgn** [comment]
Dear Prasanga,

sorry for the late reply.

I think you are running into a problem that always appears with
downsampling/upsampling. Let's say you do a downsampled convolution from a
tensor:

X: 1 2 3 4 5 6 7

to a downsampled tensor:

Y: 1 . 3 . 5 . 7

where dots indicate the pixel locations that were skipped during the
downsampling. To go back to the original resolution, you would then do an
upsampled convolution. However, note that if you had started with this
tensor:

X': 1 2 3 4 5 6 7 8

Then running the same downsampling convolution would give you the same
output tensor (Y). So, whenever you downsample, and subsequently want to
upsample back to the original tensor, you need to know what the size of the
original tensor was. This is why we encode the size of the original image
into the compressed file in our example models. It is also why there is an
output_shape argument in the transpose convolution ops
<https://www.tensorflow.org/api_docs/python/tf/nn/conv_transpose>.

Hope this helps!
Johannes.
