### ISSUE TITLE
Op type not registered 'PmfToQuantizedCdf' in binary running

### ISSUE THREAD

**Issue by lyy-zz** [tensorflow/compression#59]
**Describe the bug**
When I use `freeze_graph` to generate pb model, I get an error
`tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'PmfToQuantizedCdf' in binary running on ...`

**System:**
 -  ubuntu 18
 - python3.6 anconda
 - tf1.15
 - tensorflow-compression1.3

I want to know what the reason is or how to solve it?
Looking forward to receiving a reply, thank you!

**Comment by jonycgn** [comment]
Hi, I'm unsure exactly what your setup is, but this type of error can usually be solved by making sure that you `import tensorflow_compression`, so that the runtime knows about this op.

**Comment by lyy-zz** [comment]
Glad to receive a reply, it can solve my problem.  
Since I run `freeze_graph` by `MetaGraph` , I didn't need the code to define the graph, the package was not imported, and this error occurred.
