### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by li-zhi** [tensorflow/compression#6]
Is it possible to make a release, so that my docker file could pull a frozen version instead of the master?

**Comment by jonycgn** [comment]
Yes – we are planning to do this, but we need to figure some things out regarding binary compatibility issues and upcoming changes in TensorFlow. We'll post updates regarding that here in the next few weeks.

**Comment by jonycgn** [comment]
We have a better idea of the restructuring that's happening in TensorFlow 2 now.

We created a v1.0 release. This will be the last release which is targeted for TensorFlow 1. From now on, the master will be targeted at TensorFlow 2, and there will be pip packages for upcoming releases.

**Comment by moha23** [comment]
@jonycgn Hi, probably a silly question, I want to use the functions in tf2, but I can't find any setup.py, so I'm at a loss on how to compile/install the package for use with tf2. I have seen some people use the master version but I can't figure how to do that?

**Comment by trougnouf** [comment]
I maintain a package on the Arch Linux user repository, on https://aur.archlinux.org/packages/python-tensorflow-compression-git/

Running Arch may seem overkill to use this with TF2, but the instructions (PKGBUILD file) are plain bash that you might be able to adapt in any Linux distribution: https://aur.archlinux.org/cgit/aur.git/tree/?h=python-tensorflow-compression-git

Don't forget the python-tensorflow-probability dependency.

**Comment by moha23** [comment]
@trougnouf thanks a lot! Will try to get this working on Ubuntu.
