### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by amruz** [tensorflow/compression#60]
Thank you for the repository! If I am not wrong the current implementation does not support multiple GPU training. Any plans to do the same in future?
Also what is the average training time on V100 GPU for the entire training i.e 2 million steps

**Comment by jonycgn** [comment]
Hi, the current implementation can be used with multi-GPU training, but we don't currently provide code for it. You would mostly need to change the training loop – the layers and entropy models should support it.
