### ISSUE TITLE
Code for comparison with other compression framework

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [tensorflow/compression#65]
@jaeyounkim In your demo, you have shown a comparison with other techniques like JPG, BPG with different bitrates. I also wanted to check my images with all compression algorithms including yours. I cannot find the code for that. Please help.

**Comment by fab-jul** [comment]
Hi, are you referring to hific.github.io? If so, the script to make the demo is not open sourced. You can however easily re-create it in Python, using `Pillow` for JPEG (`Image.save(out_path, quality=quality)`) and call the `bpgenc` commandl ine tool (e.g., `subprocess.call(['bpgenc', '-q', qp, '-m', '9', '-f', '444'])`), and you can do a binary search over the `quality` and `qp` parameters to hit your desired bitrate.

To compare to our models, use `tfci.py`, as descriped in [the README](https://github.com/tensorflow/compression/tree/master/models/hific#running-models-trained-by-us-locally), or, if you use Kodak, CLIC2020, or DIV2k, you can find the reconstructions of all of our models [on the evaluation page](https://hific.github.io/raw/index.html).

Let me know if you have further questions.

**Comment by jonycgn** [comment]
Closing this as there seems to be no further activity. Please re-open if there are remaining issues.

**Comment by hzk7287** [comment]
Hi,  Can you tell me how to calculate "RD curves averaged over the Kodak image set" exactly?
In my opinion,  I use a constant Qp to encode  the whole Kodak image set, and then I can get many BPP and PSNR , finally I get the average  value of BPP and  the  average value of PSNR.  The averaged BPP  and The averaged PSNR  are a data point for drawing a RD curve.
Change Qp value, I get another data point for RD curve. 
RD curve are drawn by these averaged PSNR  and these averaged BPP.
Is it right？ 
Thanks.
