### ISSUE TITLE
AttributeError: 'PackedTensors' object has no attribute 'unpack_from_np_dtypes'

### ISSUE THREAD

**Issue by moha23** [tensorflow/compression#66]
I have been trying things out with the 2.0b1 release, using ms2020.py and everything seems to work fine except when trying to decompress from a saved  bit string (.tfci file), /I get the error that the 'packed' object has no 'unpack_from_np_dtypes' method, though I can see in packed_tensors.py that this method does exist. Any clue on where to check?

**To Reproduce**
Trained ms2020.py on couple of kodak images, compressed a single image to a .tfci bit string, and try to decompress using ms2020.py code as follows:

   
    checkpoint_dir='./checkpoints/test'
    """Compresses an image."""
    input_file = './kodak/kodim01.tfci'
    output_file = './kodak/recons.png'
    """Decompresses an image."""
    #Three integers for tensor shapes + hyperprior and N slice strings.
    np_dtypes = [np.integer] * 3 + [np.bytes_] * (NUM_SLICES + 1)
    with open(input_file, "rb") as f:
        packed = tfc.PackedTensors(f.read())
    arrays = packed.unpack_from_np_dtypes(np_dtypes)

throws the error:

> AttributeError: 'PackedTensors' object has no attribute 'unpack_from_np_dtypes'

**System (please complete the following information):**
 - OS ubuntu20.04
 - Python version Python 3.8.5
 - TensorFlow version 2.3.1
 - tensorflow-compression version 2.0b1

**Comment by moha23** [comment]
okay, i just checked the installed files and this method is actually absent though it is present in the master version here. Has this been updated i the beta 2 release? I will install that and check.

**Comment by jonycgn** [comment]
Hey, thanks for reporting this.

I think it indeed should be fixed in the second beta. The ms2020 model introduced this change in PackedTensors, and it was checked in after we released the first beta. This is probably why it fails.

I'm going to close this issue, please re-open if the problem still exists!
