### ISSUE TITLE
Remove Jupyter notebook checkpoints from version control scope

### ISSUE THREAD

**Issue by tallamjr** [tensorflow/compression#69]
**Is your feature request related to a problem? Please describe.**
When running the `toy_sources.ipynb` notebooks locally, there are additional files that are created
which perhaps do not need to be tracked such as:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        toy_sources/.ipynb_checkpoints/
```

**Describe the solution you'd like**
An update to the `.gitignore` file should correct this

**Comment by jonycgn** [comment]
Should be fixed now.
