### ISSUE TITLE
Problem when saving a model

### ISSUE THREAD

**Issue by nguerinjr** [tensorflow/compression#71]
Hello @jonycgn.

I was testing your new implementation of the model and I have identified a problem when saving the model in the last line of the training procedure.  I'm using tensorfflow 2.4.1 on cpu and the use case is the bls2017 code.

![Captura de tela 2021-03-10 184532](https://user-images.githubusercontent.com/35977339/110702323-22fbb000-81d1-11eb-8045-54588ec795fd.png)

It is currently happening in the **gdn** `call` function

![Captura de tela 2021-03-10 184553](https://user-images.githubusercontent.com/35977339/110702372-33138f80-81d1-11eb-85a1-3a2db3283a1c.png)

Tensorflow raises an exception

![Captura de tela 2021-03-10 184607](https://user-images.githubusercontent.com/35977339/110702454-4a527d00-81d1-11eb-8b12-c490be4bce43.png)

> tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph is disabled in this function. Try decorating it directly with @tf.function.

Seems like when saving a model, the keras save does not access the autograph version of the code. Therefore the python-like comparison `self.alpha == 1` triggers this exception since it becomes a tensor.

I have tried a temporary workaround with the `@tf.function`  decorator in the call (even creating an autograph sub-routine of it with the decorator). It actually works in the fit procedure, but it causes some problems later when serializing the model. 

In this case, I don't know why yet, in tensorflow/python/keras/saving/saved_model/save_impl.py, line 128, a data_structures.ListWrapper class call receives a tuple of  `layer.variables` which triggers the serialization error in an attribution sub-routine due to the immutability of tuples.

![Captura de tela 2021-03-10 191124](https://user-images.githubusercontent.com/35977339/110704932-6b689d00-81d4-11eb-983a-434d3c63c47a.png)

Actually, passing lists instead of tuples solves the problem

![Captura de tela 2021-03-10 191222](https://user-images.githubusercontent.com/35977339/110705051-96eb8780-81d4-11eb-8a8c-c6ce8c514c48.png)

But it was just a try of a temporary workaround to make it work.

**Comment by nguerinjr** [comment]
Actually, the `tf.function` workaround is ok if I cast the tuples to lists in the properties of BLS2017Model

![Captura de tela 2021-03-10 191829](https://user-images.githubusercontent.com/35977339/110705737-90a9db00-81d5-11eb-9282-578564dd811d.png)

I don't know but if it is actually an error (not something happening here because I am using it wrongly) it may require a change of call.

**Comment by nguerinjr** [comment]
Yes. The `tf.function` in the `call` and the `list` cast on the properties work.

Another workaround I have found, which neither requires internal code changes nor the casting is using the keras callback `tf.keras.callbacks.ModelCheckpoint`

![Captura de tela 2021-03-10 194433](https://user-images.githubusercontent.com/35977339/110708356-53dfe300-81d9-11eb-8e76-8b92789bfd22.png)

It did not raise the error. And it saved models in the debug folder

![Captura de tela 2021-03-10 194823](https://user-images.githubusercontent.com/35977339/110708517-943f6100-81d9-11eb-85c3-4a434bae446e.png)

**Comment by nguerinjr** [comment]
> Yes. The `tf.function` in the `call` and the `list` cast on the properties work.
> 
> Another workaround I have found, which neither requires internal code changes nor the casting is using the keras callback `tf.keras.callbacks.ModelCheckpoint`
> 
> ![Captura de tela 2021-03-10 194433](https://user-images.githubusercontent.com/35977339/110708356-53dfe300-81d9-11eb-8e76-8b92789bfd22.png)
> 
> It did not raise the error. And it saved models in the debug folder
> 
> ![Captura de tela 2021-03-10 194823](https://user-images.githubusercontent.com/35977339/110708517-943f6100-81d9-11eb-85c3-4a434bae446e.png)

Correcting my affirmation about the `tf.function` in the `call` and the `list` cast, in that workaround there are still some serialization issues:
> WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow_compression.python.layers.parameters.RDFTParameter object at 0x7f73a47c8fd0>, because it is not built.
W0310 21:50:11.985255 140136790599488 save_impl.py:77] Skipping full serialization of Keras layer > <tensorflow_compression.python.layers.parameters.RDFTParameter object at 0x7f73a47c8fd0>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow_compression.python.layers.parameters.RDFTParameter object at 0x7f73ac098520>, because it is not built.

Therefore, that workaround would require more changes. Seems like only the  `tf.keras.callbacks.ModelCheckpoint` is a full solution. And it is the simplest workaround.

I will perform additional tests to completely verify it yet.

**Comment by jonycgn** [comment]
Hi, thanks for the info. I have assessed the situation, and I think the best way forward is to rely on tf-nightly packages for now. I'm preparing a new release of TFC which should land within the next 24 hours.

**Comment by jonycgn** [comment]
We released v2.1, which should solve this problem. Note that you need a nightly version of TensorFlow 2.5 to use it.

I tested this use case specifically and couldn't reproduce it any more. Please re-open if you find that the problem is still there!

**Comment by aksinha340** [comment]
Hi @jonycgn 

I am using BLS2017 model for my experiment. I actually want to save the whole training state of the model and entropy layer to restart the training from same point . The model.save() function only saves the weight of the network and simply drops the entropy model's parameter. Further the warning says that the weights from entropy models are being dropped and may not loaded while loading the weights next time. Is there any way to save the entire model??
