### ISSUE TITLE
Error during import 

### ISSUE THREAD

**Issue by aksinha340** [tensorflow/compression#74]
The tensorflow-compression latest version shows error while importing the library in Google Colab.

import tensorflow_compression as tfc

Error:

NotFoundError: /usr/local/lib/python3.7/dist-packages/tensorflow_compression/python/ops/../../cc/libtensorflow_compression.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl14lts_2020_02_2511string_viewEOSt6vectorINS_10StackFrameESaIS7_EE

**Comment by jonycgn** [comment]
Hi, could you provide detail on which version of OS, Python, TensorFlow, and Tensorflow Compression you are using? Thanks.

**Comment by Cganzorig** [comment]
Hi,
I am having the same issue when installing and running all the tests using docker with the following commands on Windows 10. 

docker run tensorflow/tensorflow:nightly bash -c \
    "pip install tensorflow-compression &&
     python -m tensorflow_compression.all_tests"

A few days ago, it was working with no issues. The versions are as follows:

Python - 3.6.9
Tensorflow - 2.5.0
Tensorflow Compression - I guess it is the latest version.

Thanks.
Ganzorig

**Comment by jonycgn** [comment]
Hi, it may be that tf-nightly started changing their binary format. Please try running the following commands:

```
pip uninstall -y tensorflow
pip install tf-nightly==2.5.0.dev20210312
```

(either in the Docker container, or in Colab prefixed with "!")

Let me know if that works, in this case we will change the instructions.

**Comment by Cganzorig** [comment]
It works now with tf-nightly==2.5.0.dev20210312. Thanks for the help.

**Comment by jonycgn** [comment]
Should be fixed with the above commit. Please reopen if you still have problems.
