### ISSUE TITLE
Where is the entropy_models.py?

### ISSUE THREAD

**Issue by Chen8023** [tensorflow/compression#75]
I didn't find the file entropy_models.py. Is its function implemented in other files？

**Comment by jonycgn** [comment]
Yes. The same functionality is now in [continuous_batched.py](https://github.com/tensorflow/compression/blob/master/tensorflow_compression/python/entropy_models/continuous_batched.py) and [continuous_indexed.py](https://github.com/tensorflow/compression/blob/master/tensorflow_compression/python/entropy_models/continuous_indexed.py).
