### ISSUE TITLE
Saving the latent representations

### ISSUE THREAD

**Issue by jonycgn** [tensorflow/compression#77]
Hi @ankitlat,

> I am eager to know is there a way to save encoded latent representations of the pre-trained models? Presently I can only save the compressed byte stream.

Yes, you can use the "dump" subcommand of tfci.py to save any of the internal tensors of the model to NumPy format. However, you'll need to know the name of the tensor you want.

For example, in the `b2018-gdn-128-1` model, you presumably want  "analysis/layer_2/convolution:0".

Hope this helps!
Johannes

_Originally posted by @ankitlat in https://github.com/tensorflow/compression/discussions/76#discussioncomment-573780_

**Comment by qingshanzzz** [comment]
I am very eager to know where the arithmetic encoder and decoder's .so file is used.looking forward to your reply.
