### ISSUE TITLE
Error message when training bmshj2018.py with tfc 2.1: "E tensorflow/core/grappler/optimizers/meta_optimizer.cc:599] layout failed"

### ISSUE THREAD

**Issue by yiboyang** [tensorflow/compression#81]
Hello there, I'm running the latest release of tf-compression ([version 2.1](https://github.com/tensorflow/compression/releases/tag/v2.1)) and getting this error message when training bmshj2018.py. This doesn't seem to cause a problem, so it might not be an actual bug. 

**To Reproduce**
Run training with [`bmshj2018.py` @ f9edc94](https://github.com/tensorflow/compression/blob/f9edc949fa58381ffafa5aa8cb37dc8c3ce50e7f/models/bmshj2018.py
), e.g., with the following command:
`python bmshj2018.py -V   train --num_filters 192 --lambda 0.001 --train_glob '/path/to/imgs/*.png' --epochs 2 --steps_per_epoch 10`

**Expected behavior**
An error message like this appears at the beginning of training:

```                                                                                                                     
2021-04-25 19:41:36.471487: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:599] layout failed: Invalid argument: Size of values 0 does not match size of perm
utation 4 @ fanin shape ingradient_tape/bmsh_j2018model/location_scale_indexed_entropy_model/bmsh_j2018model_location_scale_indexed_entropy_model_NoisyNormal_1_1/log_
prob/SelectV2_1-1-TransposeNHWCToNCHW-LayoutOptimizer
```
But training runs OK. Compression/decompression with the trained model also seems to work fine.

**System (please complete the following information):**
 - OS: Ubuntu 18
 - Python version [also include how installed: anaconda, apt-get, etc.]: 3.7; see below for full info.
 - TensorFlow version [also include how installed: pip, conda, Docker, etc.]: tf-nightly==2.5.0.dev20210312
 - tensorflow-compression version: 2.1

**Additional context**
The Python installation was created with
```
conda create --prefix /tmp/test_env python=3.7
conda activate /tmp/test_env
pip install tf-nightly==2.5.0.dev20210312 tensorflow-compression==2.1
```

**Comment by jonycgn** [comment]
Hi Yibo, thanks for reporting. You can safely ignore this message. It indicates that an optimization of the model graph failed, so perhaps it is running a bit slower than it could, but it should not affect the training itself. Perhaps it is a bug in the TF  optimizer.
