### ISSUE TITLE
more details about how to train a model using custom dataset?

### ISSUE THREAD

**Issue by cheng-linkai** [tensorflow/compression#96]
has any friend successfully trained a model using a custom dataset? Could you tell me more details about that? I can not find _get_dataset called in train.py mentioned in readme.Thank you in advance.

**Comment by Labo9527** [comment]
I use local CLIC to train my model (bls2017.py) with the parameter like "--train_glob=/path_to_my_clic/clic/**/*.png". Maybe you can try it to use your own dataset by replacing the path.

**Comment by cheng-linkai** [comment]
> I use local CLIC to train my model (bls2017.py) with the parameter like "--train_glob=/path_to_my_clic/clic/**/*.png". Maybe you can try it to use your own dataset by replacing the path.

Thanks a lot

**Comment by AliMaleky7997** [comment]
> I use local CLIC to train my model (bls2017.py) with the parameter like "--train_glob=/path_to_my_clic/clic/**/*.png". Maybe you can try it to use your own dataset by replacing the path.

Hi. I just had a quick question. As the code is in TensorFlow 1.15 and tfds 1.0.1 does not support CLIC, I was wondering how you managed to use CLIC to train your model. I could not find a download link for the CLIC dataset to create my own custom dataset. Thanks in advance.

**Comment by jonycgn** [comment]
Hi, the CLIC dataset is in TensorFlow Datasets: https://www.tensorflow.org/datasets/catalog/clic

Please check the documentation there to see how to download it!
